---

plugins:
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]